# git add .
# git commit -m "abc"
# git push

remote_theme: just-the-docs/just-the-docs

# Site settings
title: Khánh Nguyễn  #title of the page
description: Enter description here
##baseurl:  # the subpath of your site, e.g. /blog #usually not needed
#url: "https://just-the-docs.github.io" # the base hostname & protocol for your site, e.g. http://example.com #need to input
url: "https://nghkhanh.github.io"

permalink: pretty
exclude: ["node_modules/", "*.gemspec", "*.gem", "Gemfile", "Gemfile.lock", "package.json", "package-lock.json",  "script/", "LICENSE.txt", "lib/", "bin/", "README.md", "Rakefile"
, "docs/tests/", "*.sh"
]

# Set a path/url to a logo that will be displayed instead of the title
# logo: "/docs/jordan-whitt-EerxztHCjM8-unsplash.jpg" #need to add a logo here later

# Enable or disable the site search
# Supports true (default) or false
search_enabled: true
search:
  # Split pages into sections that can be searched individually
  heading_level: 2
  # Maximum amount of previews per search result
  previews: 2
  # Maximum amount of words to display before a matched word in the preview
  preview_words_before: 3
  # Maximum amount of words to display after a matched word in the preview
  preview_words_after: 5
  # Set the search token separator
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/ #this is the default
  # Display the relative url in search results
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  button: false

# Enable or disable heading anchors
heading_anchors: true
  # Display the relative url in search results
  # Display the relative url in search results

# Aux links for the upper right navigation
#aux_links:
  #"Link name":
    #- "" #link would go here in the quotes
    
# Makes Aux links open in a new tab. Default is false
#aux_links_new_tab: false

# Sort order for navigation links
nav_sort: case_sensitive # Capital letters sorted before lowercase (default)


# Footer content

# Back to top link
back_to_top: true
back_to_top_text: "Top"

# footer_content: "Insert footer text" #needs to be added

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Footer "Edit this page on GitHub" link text
gh_edit_link: false # show or hide edit this page link
#gh_edit_link_text: "" #this would be the text shown
#gh_edit_repository: "" # the github URL for your repo
#gh_edit_branch: "main" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
#gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

# Color scheme currently only supports "dark", "light"/nil (default), or a custom scheme that you define
color_scheme: nil

plugins:
  - jekyll-seo-tag
  
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
  # ignore:
  #   envs: all

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "9.1.3"

